-- 1. Empleados ordenados alfabéticamente (Z...A)
SELECT NOMBRES
FROM EMPLEADOS
ORDER BY NOMBRES DESC;

-- 2. Empleados de Soporte
SELECT E.NOMBRES, P.PUESTO, L.LOCALIDAD
FROM EMPLEADOS E
JOIN PUESTOS P ON E.PUESTO_ID = P.ID
JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE P.PUESTO = 'Soporte';

-- 3. Nombres que terminan con 'o'
SELECT NOMBRES
FROM EMPLEADOS
WHERE NOMBRES LIKE '%o';

-- 4. Empleados en Carlos Paz
SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD
FROM EMPLEADOS E
JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Carlos Paz';

-- 5. Sueldos entre 10000 y 13000
SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD
FROM EMPLEADOS E
JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE E.SUELDO BETWEEN 10000 AND 13000;

-- 6. Departamentos con más de 5 empleados
SELECT D.DENOMINACION, COUNT(E.ID) AS CantidadEmpleados
FROM DEPARTAMENTOS D
JOIN EMPLEADOS E ON D.ID = E.DEPARTAMENTO_ID
GROUP BY D.DENOMINACION
HAVING COUNT(E.ID) > 5;

-- 7. Empleados en Córdoba con puesto de Analista o Programador
SELECT E.NOMBRES
FROM EMPLEADOS E
JOIN PUESTOS P ON E.PUESTO_ID = P.ID
JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Córdoba'
  AND P.PUESTO IN ('Analista', 'Programador');

-- 8. Sueldo medio de todos los empleados
SELECT AVG(SUELDO) AS SueldoMedio
FROM EMPLEADOS;

-- 9. Máximo sueldo en el departamento 10
SELECT MAX(SUELDO) AS SueldoMaximo
FROM EMPLEADOS
WHERE DEPARTAMENTO_ID = 10;

-- 10. Sueldo mínimo en el departamento Soporte
SELECT MIN(E.SUELDO) AS SueldoMinimo
FROM EMPLEADOS E
JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
WHERE D.DENOMINACION = 'Soporte';

-- 11. Suma de sueldos por puesto
SELECT P.PUESTO, SUM(E.SUELDO) AS TotalSueldos
FROM EMPLEADOS E
JOIN PUESTOS P ON E.PUESTO_ID = P.ID
GROUP BY P.PUESTO;
